name: Build
on:
  push:
    branches:
      - 'ver/1.17.1'
  pull_request:
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: 'Upload artifact to this run? [yes | no]'
        required: false
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Upload Artifact
        if: ${{ contains(github.event.inputs.upload_artifact, 'yes') }}
        uses: actions/upload-artifact@v1.0.0
        with:
          name: PvPLiteServer-1.17.1-R0.1-SNAPSHOT.jar
          path: PvPLite-Server/build/libs/PvPLiteServer-1.17.1-R0.1-SNAPSHOT.jar
